backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "Index Page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: markdown }
          - {
              label: Blurbs,
              name: blurbs,
              widget: list,
              fields:
                [
                  { label: Description, name: description, widget: markdown },
                  {
                    label: Image,
                    name: image,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: string }
          - label: "Avatars"
            name: "avatars"
            widget: "list"
            fields:
              - label: "Avatar"
                name: "avatar"
                widget: "object"
                fields:
                  - { label: "Header", name: "header", widget: "string" }
                  - label: "Image"
                    name: "image"
                    widget: "image"
                  - {
                      label: "Description",
                      name: "description",
                      widget: "string",
                    }
          - { label: "Body", name: "body", widget: markdown }
          - label: "Partners"
            name: "partners"
            widget: "list"
            fields:
              - label: "Partner"
                name: "partner"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - {
                      label: "PartnerName",
                      name: "partnerName",
                      widget: "string",
                    }
      - file: "src/pages/plans/index.md"
        label: Plans
        name: Plans
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "plans-page",
            }
          - { label: Title, name: title, widget: string }
          - label: Plans
            name: plans
            widget: list
            fields:
              - label: Plan
                name: Plan
                widget: object
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Price, name: price, widget: number }
                  - label: Dishes
                    name: dishes
                    widget: list
                    fields:
                      - { label: Name, name: name, widget: string }
                      - {
                          label: Description,
                          name: description,
                          widget: string,
                        }
                      - {
                          label: Allergens,
                          name: allergens,
                          widget: string,
                          required: false,
                        }
                      - label: Image
                        name: image
                        widget: object
                        fields:
                          - { label: Image, name: src, widget: image }
                          - {
                              label: Alt,
                              name: alt,
                              widget: string,
                              required: false,
                            }